version: '2.1'
services:
  fhirkeycloak:
    image: fhirkeycloak
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=deviam
      - KEYCLOAK_PASSWORD=deviam
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
